#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa ./ebin -sasl errlog_type error -boot start_sasl

main(_) ->
    etap:plan(64),
    etap:is("\"foo \\$bar\\\"\\`' baz\"", mochiweb_util:shell_quote("foo $bar\"`' baz"), "shell_quote/1"),
    etap:is("$bling$ `word`!\n", mochiweb_util:cmd(["echo", "$bling$ `word`!"]), "cmd/1"),
    etap:is("\"echo\" \"\\$bling\\$ \\`word\\`!\"", mochiweb_util:cmd_string(["echo", "$bling$ `word`!"]), "cmd_string/1"),
    etap:is({"multipart/form-data", [{"boundary", "AaB03x"}]}, mochiweb_util:parse_header("multipart/form-data; boundary=AaB03x"), "parse_header/1"),
    etap:is("text/plain", mochiweb_util:guess_mime(""), "guess_mime/1"),
    etap:is("text/plain", mochiweb_util:guess_mime(".text"), "guess_mime/1"),
    etap:is("application/zip", mochiweb_util:guess_mime(".zip"), "guess_mime/1"),
    etap:is("application/zip", mochiweb_util:guess_mime("x.zip"), "guess_mime/1"),
    etap:is("text/html", mochiweb_util:guess_mime("x.html"), "guess_mime/1"),
    etap:is("application/xhtml+xml", mochiweb_util:guess_mime("x.xhtml"), "guess_mime/1"),
    etap:is({"", "foo/bar"}, mochiweb_util:path_split("/foo/bar"), "path_split/1"),
    etap:is({"foo", "bar"}, mochiweb_util:path_split("foo/bar"), "path_split/1"),
    etap:is({"bar", ""}, mochiweb_util:path_split("bar"), "path_split/1"),
    etap:is({"", "", "/foo", "", "bar?baz"}, mochiweb_util:urlsplit("/foo#bar?baz"), "urlsplit/1"),
    etap:is({"http", "host:port", "/foo", "", "bar?baz"}, mochiweb_util:urlsplit("http://host:port/foo#bar?baz"), "urlsplit/1"),
    etap:is({"/foo/bar", "", ""}, mochiweb_util:urlsplit_path("/foo/bar"), "urlsplit_path/1"),
    etap:is({"/foo", "baz", ""}, mochiweb_util:urlsplit_path("/foo?baz"), "urlsplit_path/1"),
    etap:is({"/foo", "", "bar?baz"}, mochiweb_util:urlsplit_path("/foo#bar?baz"), "urlsplit_path/1"),
    etap:is({"/foo", "", "bar?baz#wibble"}, mochiweb_util:urlsplit_path("/foo#bar?baz#wibble"), "urlsplit_path/1"),
    etap:is({"/foo", "bar", "baz"}, mochiweb_util:urlsplit_path("/foo?bar#baz"), "urlsplit_path/1"),
    etap:is({"/foo", "bar?baz", "baz"}, mochiweb_util:urlsplit_path("/foo?bar?baz#baz"), "urlsplit_path/1"),
    etap:is("/foo#bar?baz", mochiweb_util:urlunsplit({"", "", "/foo", "", "bar?baz"}), "urlunsplit/1"),
    etap:is("http://host:port/foo#bar?baz", mochiweb_util:urlunsplit({"http", "host:port", "/foo", "", "bar?baz"}), "urlunsplit/1"),
    etap:is("/foo/bar", mochiweb_util:urlunsplit_path({"/foo/bar", "", ""}), "urlunsplit_path/2"),
    etap:is("/foo?baz", mochiweb_util:urlunsplit_path({"/foo", "baz", ""}), "urlunsplit_path/2"),
    etap:is("/foo#bar?baz", mochiweb_util:urlunsplit_path({"/foo", "", "bar?baz"}), "urlunsplit_path/2"),
    etap:is("/foo#bar?baz#wibble", mochiweb_util:urlunsplit_path({"/foo", "", "bar?baz#wibble"}), "urlunsplit_path/2"),
    etap:is("/foo?bar#baz", mochiweb_util:urlunsplit_path({"/foo", "bar", "baz"}), "urlunsplit_path/2"),
    etap:is("/foo?bar?baz#baz", mochiweb_util:urlunsplit_path({"/foo", "bar?baz", "baz"}), "urlunsplit_path/2"),
    etap:is("foo,bar,baz", mochiweb_util:join(["foo", "bar", "baz"], $,), "join/2"),
    etap:is("foo,bar,baz", mochiweb_util:join(["foo", "bar", "baz"], ","), "join/2"),
    etap:is("foo bar", mochiweb_util:join([["foo", " bar"]], ","), "join/2"),
    etap:is("foo bar,baz", mochiweb_util:join([["foo", " bar"], "baz"], ","), "join/2"),
    etap:is("foo", mochiweb_util:join(["foo"], ","), "join/2"),
    etap:is("foobarbaz", mochiweb_util:join(["foo", "bar", "baz"], ""), "join/2"),
    etap:is("foo", mochiweb_util:quote_plus(foo), "quote_plus/1"),
    etap:is("1", mochiweb_util:quote_plus(1), "quote_plus/1"),
    etap:is("1.1", mochiweb_util:quote_plus(1.1), "quote_plus/1"),
    etap:is("foo", mochiweb_util:quote_plus("foo"), "quote_plus/1"),
    etap:is("foo+bar", mochiweb_util:quote_plus("foo bar"), "quote_plus/1"),
    etap:is("foo%0A", mochiweb_util:quote_plus("foo\n"), "quote_plus/1"),
    etap:is("foo%0A", mochiweb_util:quote_plus("foo\n"), "quote_plus/1"),
    etap:is("foo%3B%26%3D", mochiweb_util:quote_plus("foo;&="), "quote_plus/1"),
    etap:is("foo bar", mochiweb_util:unquote("foo+bar"), "unquote/1"),
    etap:is("foo bar", mochiweb_util:unquote("foo%20bar"), "unquote/1"),
    etap:is("foo\r\n", mochiweb_util:unquote("foo%0D%0A"), "unquote/1"),
    etap:is("foo=bar&baz=wibble+%0D%0A&z=1", mochiweb_util:urlencode([{foo, "bar"}, {"baz", "wibble \r\n"}, {z, 1}]), "urlencode/1"),
    etap:is([{"foo", "bar"}, {"baz", "wibble \r\n"}, {"z", "1"}], mochiweb_util:parse_qs("foo=bar&baz=wibble+%0D%0A&z=1"), "parse_qs/1"),
    etap:is({"foo", "", ""}, mochiweb_util:partition("foo", "/"), "partition/2"),
    etap:is({"foo", "/", "bar"}, mochiweb_util:partition("foo/bar", "/"), "partition/2"),
    etap:is({"foo", "/", ""}, mochiweb_util:partition("foo/", "/"), "partition/2"),
    etap:is({"", "/", "bar"}, mochiweb_util:partition("/bar", "/"), "partition/2"),
    etap:is({"f", "oo/ba", "r"}, mochiweb_util:partition("foo/bar", "oo/ba"), "partition/2"),
    etap:is("foo", mochiweb_util:safe_relative_path("foo"), "safe_relative_path/1"),
    etap:is("foo/", mochiweb_util:safe_relative_path("foo/"), "safe_relative_path/1"),
    etap:is("foo", mochiweb_util:safe_relative_path("foo/bar/.."), "safe_relative_path/1"),
    etap:is("bar", mochiweb_util:safe_relative_path("foo/../bar"), "safe_relative_path/1"),
    etap:is("bar/", mochiweb_util:safe_relative_path("foo/../bar/"), "safe_relative_path/1"),
    etap:is("", mochiweb_util:safe_relative_path("foo/.."), "safe_relative_path/1"),
    etap:is("", mochiweb_util:safe_relative_path("foo/../"), "safe_relative_path/1"),
    etap:is(undefined, mochiweb_util:safe_relative_path("/foo"), "safe_relative_path/1"),
    etap:is(undefined, mochiweb_util:safe_relative_path("../foo"), "safe_relative_path/1"),
    etap:is(undefined, mochiweb_util:safe_relative_path("foo/../.."), "safe_relative_path/1"),
    etap:is(undefined, mochiweb_util:safe_relative_path("foo//"), "safe_relative_path/1"),
    etap:end_tests().
